# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tzc < Formula
  desc "Timezone converter TUI for the terminal"
  homepage "https://github.com/kjhaber/tzc"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kjhaber/tzc/releases/download/v0.1.0/tzc_0.1.0_darwin_amd64.tar.gz"
      sha256 "cb087f85c3a735c6d31e10457686620f8e72d9f99d84cf01474c235707f77e76"

      define_method(:install) do
        bin.install "tzc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kjhaber/tzc/releases/download/v0.1.0/tzc_0.1.0_darwin_arm64.tar.gz"
      sha256 "95ff46d6cbecb8163329b82dfc8e609cbf0d428c8232152799792624a4ddd1b8"

      define_method(:install) do
        bin.install "tzc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kjhaber/tzc/releases/download/v0.1.0/tzc_0.1.0_linux_amd64.tar.gz"
      sha256 "50af8f0bbe67e465fca8b39270b8cc03c43dc6e83f3b850965767bdfd3fa0bbc"
      define_method(:install) do
        bin.install "tzc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kjhaber/tzc/releases/download/v0.1.0/tzc_0.1.0_linux_arm64.tar.gz"
      sha256 "b17145f6f6b48f514320413c9f04fc8628ca33f82f72d6cb94b86c83c5d79509"
      define_method(:install) do
        bin.install "tzc"
      end
    end
  end

  test do
    system "#{bin}/tzc", "--version"
  end
end
