# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wn < Formula
  desc "What's Next — local task/work item tracker"
  homepage "https://github.com/kjhaber/wn"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kjhaber/wn/releases/download/v0.1.0/wn_0.1.0_darwin_amd64.tar.gz"
      sha256 "afba175e8342b472cfbfc7cfe0f4da47060955598c2d8acdd8f437df5cba9a43"

      define_method(:install) do
        bin.install "wn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kjhaber/wn/releases/download/v0.1.0/wn_0.1.0_darwin_arm64.tar.gz"
      sha256 "1bfd485682f46fb9c14c6bb1d679c375516d791a34b6ac05b277102fca52e5ed"

      define_method(:install) do
        bin.install "wn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kjhaber/wn/releases/download/v0.1.0/wn_0.1.0_linux_amd64.tar.gz"
      sha256 "2e498c64bf685347b623d6006ec0789cf41f8b9150d1464d8d3064396b852455"
      define_method(:install) do
        bin.install "wn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kjhaber/wn/releases/download/v0.1.0/wn_0.1.0_linux_arm64.tar.gz"
      sha256 "1a2e014a92822d8cc64a565800e2d48e34156d644ba25e349e2331b0236b0a97"
      define_method(:install) do
        bin.install "wn"
      end
    end
  end

  test do
    system "#{bin}/wn", "--version"
  end
end
