# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wn < Formula
  desc "What's Next — local task/work item tracker"
  homepage "https://github.com/kjhaber/wn"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kjhaber/wn/releases/download/v0.2.0/wn_0.2.0_darwin_amd64.tar.gz"
      sha256 "b2cbcf488358f2bbf523842fb739f2fdceeeccf86ae8697fec740dabebf1504b"

      define_method(:install) do
        bin.install "wn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kjhaber/wn/releases/download/v0.2.0/wn_0.2.0_darwin_arm64.tar.gz"
      sha256 "60718e82d114ee027b50ad13943842c5b4b0eb0c3bd58cac5cee17014de0ddd6"

      define_method(:install) do
        bin.install "wn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kjhaber/wn/releases/download/v0.2.0/wn_0.2.0_linux_amd64.tar.gz"
      sha256 "848bff3290b707e0598899cf30c822fa61a4b45b12664176b6f5e8c449f7cde8"
      define_method(:install) do
        bin.install "wn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kjhaber/wn/releases/download/v0.2.0/wn_0.2.0_linux_arm64.tar.gz"
      sha256 "0a41e5152a9dac9e54567b5407b3efdb89b519d16c5da2534fac3313f75fd7e0"
      define_method(:install) do
        bin.install "wn"
      end
    end
  end

  test do
    system "#{bin}/wn", "--version"
  end
end
