# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wn < Formula
  desc "What's Next — local task/work item tracker"
  homepage "https://github.com/kjhaber/wn"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kjhaber/wn/releases/download/v0.5.0/wn_0.5.0_darwin_amd64.tar.gz"
      sha256 "6fb0784f8ed7692b6701f82e43f1b4eac21d8424305c9a0d518b4796daf1cdab"

      define_method(:install) do
        bin.install "wn"
        bash_completion.install "completions/wn.bash"
        zsh_completion.install "completions/_wn"
        fish_completion.install "completions/wn.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kjhaber/wn/releases/download/v0.5.0/wn_0.5.0_darwin_arm64.tar.gz"
      sha256 "fefb82ecf0bac14af224cff190e53891a5b12ad2e0f092eba961762cbfdb544d"

      define_method(:install) do
        bin.install "wn"
        bash_completion.install "completions/wn.bash"
        zsh_completion.install "completions/_wn"
        fish_completion.install "completions/wn.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kjhaber/wn/releases/download/v0.5.0/wn_0.5.0_linux_amd64.tar.gz"
      sha256 "eac5292ff95fcea176ff1fcaba5752d1ca9662653205ebd2ada0bd422538cb5f"
      define_method(:install) do
        bin.install "wn"
        bash_completion.install "completions/wn.bash"
        zsh_completion.install "completions/_wn"
        fish_completion.install "completions/wn.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kjhaber/wn/releases/download/v0.5.0/wn_0.5.0_linux_arm64.tar.gz"
      sha256 "11f3827f16d6ba965ebad5736db45274495912076e2406c67209960a6eaea643"
      define_method(:install) do
        bin.install "wn"
        bash_completion.install "completions/wn.bash"
        zsh_completion.install "completions/_wn"
        fish_completion.install "completions/wn.fish"
      end
    end
  end

  test do
    system "#{bin}/wn", "--version"
  end
end
