# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aw < Formula
  desc "Monitor coding agents across tmux sessions"
  homepage "https://github.com/kjhaber/aw"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kjhaber/aw/releases/download/v0.1.7/aw_0.1.7_darwin_amd64.tar.gz"
      sha256 "8fcc6b30825f250e184cc7e9c484adff79b1a4c45a7b35de39a98e5679eb795f"

      define_method(:install) do
        bin.install "aw"
        (bash_completion/"aw").write Utils.safe_popen_read("#{bin}/aw", "completion", "bash")
        (zsh_completion/"_aw").write Utils.safe_popen_read("#{bin}/aw", "completion", "zsh")
        (fish_completion/"aw.fish").write Utils.safe_popen_read("#{bin}/aw", "completion", "fish")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kjhaber/aw/releases/download/v0.1.7/aw_0.1.7_darwin_arm64.tar.gz"
      sha256 "20f42342fefc0d7e1ef10b7e80c0ea236dda1643ad196e867e2d8fa2e56e8495"

      define_method(:install) do
        bin.install "aw"
        (bash_completion/"aw").write Utils.safe_popen_read("#{bin}/aw", "completion", "bash")
        (zsh_completion/"_aw").write Utils.safe_popen_read("#{bin}/aw", "completion", "zsh")
        (fish_completion/"aw.fish").write Utils.safe_popen_read("#{bin}/aw", "completion", "fish")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kjhaber/aw/releases/download/v0.1.7/aw_0.1.7_linux_amd64.tar.gz"
      sha256 "3102775fb8e653d012d64b034b30c224e972fd23c3dcf81e58d04125e2b1d58d"
      define_method(:install) do
        bin.install "aw"
        (bash_completion/"aw").write Utils.safe_popen_read("#{bin}/aw", "completion", "bash")
        (zsh_completion/"_aw").write Utils.safe_popen_read("#{bin}/aw", "completion", "zsh")
        (fish_completion/"aw.fish").write Utils.safe_popen_read("#{bin}/aw", "completion", "fish")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kjhaber/aw/releases/download/v0.1.7/aw_0.1.7_linux_arm64.tar.gz"
      sha256 "480497db7f8c114bab3d7d4e19e490bc01a3f1f916f54d231c4d3c744a479a0b"
      define_method(:install) do
        bin.install "aw"
        (bash_completion/"aw").write Utils.safe_popen_read("#{bin}/aw", "completion", "bash")
        (zsh_completion/"_aw").write Utils.safe_popen_read("#{bin}/aw", "completion", "zsh")
        (fish_completion/"aw.fish").write Utils.safe_popen_read("#{bin}/aw", "completion", "fish")
      end
    end
  end

  test do
    system "#{bin}/aw", "--version"
  end
end
