# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tzc < Formula
  desc "Timezone converter TUI for the terminal"
  homepage "https://github.com/kjhaber/tzc"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kjhaber/tzc/releases/download/v0.1.2/tzc_0.1.2_darwin_amd64.tar.gz"
      sha256 "37866102da32004694967f56c71e6cf8531b7b95f55fa209ca4cd7adae50379d"

      define_method(:install) do
        bin.install "tzc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kjhaber/tzc/releases/download/v0.1.2/tzc_0.1.2_darwin_arm64.tar.gz"
      sha256 "b1b158c2b0856251855e317d51b5a987580d8da09b16d265411002b0f4196a31"

      define_method(:install) do
        bin.install "tzc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kjhaber/tzc/releases/download/v0.1.2/tzc_0.1.2_linux_amd64.tar.gz"
      sha256 "a3b1f04ff6a432f444d15bd7c95493105498edc9b03415448bdaf6913e02f0e2"
      define_method(:install) do
        bin.install "tzc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kjhaber/tzc/releases/download/v0.1.2/tzc_0.1.2_linux_arm64.tar.gz"
      sha256 "9dd214990857f85b742f1b7f7e9022e6aef78ee7507bd1b90696f85b5557f124"
      define_method(:install) do
        bin.install "tzc"
      end
    end
  end

  test do
    system "#{bin}/tzc", "--version"
  end
end
