# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tzc < Formula
  desc "Timezone converter TUI for the terminal"
  homepage "https://github.com/kjhaber/tzc"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kjhaber/tzc/releases/download/v0.1.1/tzc_0.1.1_darwin_amd64.tar.gz"
      sha256 "7c2cfcd3cd6e99707b7f92936022582187008db6931e7d4fbd67e8b5fd2c3bd2"

      define_method(:install) do
        bin.install "tzc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kjhaber/tzc/releases/download/v0.1.1/tzc_0.1.1_darwin_arm64.tar.gz"
      sha256 "506e7f362c1e6d38d52d276ebb0860d325d7014b42a81ab301e470801b28bbc3"

      define_method(:install) do
        bin.install "tzc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kjhaber/tzc/releases/download/v0.1.1/tzc_0.1.1_linux_amd64.tar.gz"
      sha256 "9ee1f94382b3b6582d6f8558933d36bf930f67e0c78b7326a5c56352585adac5"
      define_method(:install) do
        bin.install "tzc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kjhaber/tzc/releases/download/v0.1.1/tzc_0.1.1_linux_arm64.tar.gz"
      sha256 "c208ca019f3ba88b8e0bc3ca4dba3a8f294230c14a686370925eaae25659434e"
      define_method(:install) do
        bin.install "tzc"
      end
    end
  end

  test do
    system "#{bin}/tzc", "--version"
  end
end
